# apiVersion: apps/v1beta1
# kind: Deployment
# metadata:
#   name: backend
# spec:
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#       - name: backend
#         image: maduflavins/spleetbackend
#         ports:
#         - containerPort: 3001
#         env:
#         - name: NODE_ENV
#           value: production
#         - name: MONGODB_URI
#           valueFrom:
#             secretKeyRef:
#               name: database-secret-config
#               key: mongouri



apiVersion: apps/v1
kind: Deployment
metadata:
  name: spleetbackend
  labels:
    app: spleetbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spleetbackend
  template:
    metadata:
      labels:
        app: spleetbackend
    spec:
      containers:
      - name: spleetbackend
        image: maduflavins/spleetbackend
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: db-secret-config
              key: mongouri