apiVersion: v1
kind: Service
metadata:
  name: spleetbackend
  namespace: default
  labels:
    app: spleetbackend
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: http
      name: http
  selector:
    app: spleetbackend